apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.fibonacci.appName }}
  labels:
    app: {{ .Values.fibonacci.appName }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.fibonacci.appName }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: {{ .Values.fibonacci.appName }}
        image: "{{ .Values.fibonacci.deployment.image.repository }}:{{ .Values.fibonacci.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.fibonacci.deployment.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.fibonacci.service.internalPort }}
        resources:
          limits:
            cpu: {{ .Values.fibonacci.deployment.limits.cpu }}
            memory: {{ .Values.fibonacci.deployment.limits.memory }}