apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.kubernetesapi.appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.kubernetesapi.appName }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  jobTargetUrl: {{ .Values.kubernetesapi.deployment.env.jobTargetUrl }}
  corsOrigins: {{ .Values.kubernetesapi.deployment.env.corsOrigins }}