---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kubernetesapi.deployment.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.kubernetesapi.appName }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ .Values.kubernetesapi.deployment.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.kubernetesapi.appName }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create","get","list","delete"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get"]
- apiGroups: [""] 
  resources: ["events"] 
  verbs: ["list"] 
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ .Values.kubernetesapi.deployment.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.kubernetesapi.appName }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.kubernetesapi.deployment.serviceAccountName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.kubernetesapi.deployment.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Values.kubernetesapi.deployment.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.kubernetesapi.appName }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.kubernetesapi.deployment.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.kubernetesapi.appName }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.kubernetesapi.deployment.serviceAccountName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.kubernetesapi.deployment.serviceAccountName }}
    namespace: {{ .Release.Namespace }}