apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.webui.appName }}
  labels:
    app: {{ .Values.webui.appName }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  kubernetesApiUrl: {{ .Values.webui.deployment.env.kubernetesApiUrl }}